export const FontFamiliesRoboto : string;
export const LineHeights0 : string;
export const LineHeights1 : string;
export const LineHeights2 : string;
export const LineHeights3 : string;
export const LineHeights4 : string;
export const LineHeights5 : string;
export const LineHeights6 : string;
export const LineHeights7 : string;
export const LineHeights8 : string;
export const LineHeights9 : string;
export const LineHeights10 : string;
export const LineHeights11 : number;
export const LineHeights12 : number;
export const LineHeights13 : number;
export const LineHeights14 : number;
export const LineHeights15 : number;
export const LineHeights16 : number;
export const LineHeights17 : number;
export const LineHeights18 : number;
export const FontWeightsLight : string;
export const FontWeightsRegular : string;
export const FontWeightsMedium : string;
export const FontSize0 : number;
export const FontSize1 : number;
export const FontSize2 : number;
export const FontSize3 : number;
export const FontSize4 : number;
export const FontSize5 : number;
export const FontSize6 : number;
export const FontSize7 : number;
export const FontSize8 : number;
export const FontSize9 : number;
export const FontSize10 : number;
export const FontSize11 : number;
export const LetterSpacing0 : number;
export const LetterSpacing1 : number;
export const LetterSpacing2 : number;
export const LetterSpacing3 : number;
export const LetterSpacing4 : number;
export const LetterSpacing5 : number;
export const LetterSpacing6 : number;
export const LetterSpacing7 : number;
export const LetterSpacing8 : number;
export const LetterSpacing9 : number;
export const LetterSpacing10 : number;
export const LetterSpacing11 : number;
export const ParagraphSpacingNone : number;
export const ComponentsAlertTitle : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsAvatarInitials : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsBadgeLabel : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsButtonLarge : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsButtonMedium : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsButtonSmall : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsInputLabel : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsHelperText : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsInputText : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsChipLabel : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsTooltipLabel : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsTableHeader : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsMenuItem : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsMenuItemDense : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsListSubheader : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const ComponentsBottomNavigationActiveLabel : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TextCaseNone : string;
export const TextCaseUppercase : string;
export const TextDecorationNone : string;
export const ParagraphIndentNone : number;
export const InputStandardEnabledBorder : string;
export const InputStandardHoverBorder : string;
export const InputFilledEnabledFill : string;
export const InputFilledHoverFill : string;
export const InputOutlinedEnabledBorder : string;
export const InputOutlinedHoverBorder : string;
export const SwitchKnobFill : string;
export const SwitchSlideFill : string;
export const AvatarFill : string;
export const ChipDefaultCloseFill : string;
export const ChipDefaultHoverFill : string;
export const ChipDefaultEnabledBorder : string;
export const AlertErrorContent : string;
export const AlertErrorFill : string;
export const AlertWarningContent : string;
export const AlertWarningFill : string;
export const AlertInfoContent : string;
export const AlertInfoFill : string;
export const AlertSuccessContent : string;
export const AlertSuccessFill : string;
export const BackdropFill : string;
export const BreadcrumbsCollapseFill : string;
export const AppbarDefaultFill : string;
export const RatingEnabledBorder : string;
