export const Divider : string;
export const TextPrimary : string;
export const TextSecondary : string;
export const TextDisabled : string;
export const PrimaryMain : string;
export const PrimaryDark : string;
export const PrimaryLight : string;
export const PrimaryContrast : string;
export const PrimaryStatesHover : string;
export const PrimaryStatesSelected : string;
export const PrimaryStatesFocus : string;
export const PrimaryStatesFocusVisible : string;
export const PrimaryStatesOutlinedBorder : string;
export const SecondaryMain : string;
export const SecondaryDark : string;
export const SecondaryLight : string;
export const SecondaryContrast : string;
export const SecondaryStatesHover : string;
export const SecondaryStatesSelected : string;
export const SecondaryStatesFocus : string;
export const SecondaryStatesFocusVisible : string;
export const SecondaryStatesOutlinedBorder : string;
export const ActionHover : string;
export const ActionSelected : string;
export const ActionDisabledBackground : string;
export const ActionFocus : string;
export const ActionDisabled : string;
export const ActionActive : string;
export const ActionHoverOpacity : number;
export const ActionSelectedOpacity : number;
export const ActionDisabledOpacity : number;
export const ActionFocusOpacity : number;
export const ActionActiveChannel : string;
export const ActionSelectedChannel : string;
export const ErrorMain : string;
export const ErrorDark : string;
export const ErrorLight : string;
export const ErrorContrast : string;
export const ErrorStatesHover : string;
export const ErrorStatesSelected : string;
export const ErrorStatesFocusVisible : string;
export const ErrorStatesOutlinedBorder : string;
export const WarningMain : string;
export const WarningDark : string;
export const WarningLight : string;
export const WarningContrast : string;
export const WarningStatesHover : string;
export const WarningStatesSelected : string;
export const WarningStatesFocusVisible : string;
export const WarningStatesOutlinedBorder : string;
export const InfoMain : string;
export const InfoDark : string;
export const InfoLight : string;
export const InfoContrast : string;
export const InfoStatesHover : string;
export const InfoStatesSelected : string;
export const InfoStatesFocusVisible : string;
export const InfoStatesOutlinedBorder : string;
export const SuccessMain : string;
export const SuccessDark : string;
export const SuccessLight : string;
export const SuccessContrast : string;
export const SuccessStatesHover : string;
export const SuccessStatesSelected : string;
export const SuccessStatesFocusVisible : string;
export const SuccessStatesOutlinedBorder : string;
export const InheritWhiteHover : string;
export const InheritWhiteSelected : string;
export const InheritWhiteFocus : string;
export const InheritWhiteMain : string;
export const InheritWhiteFocusVisible : string;
export const InheritTextPrimaryHover : string;
export const InheritTextPrimarySelected : string;
export const InheritTextPrimaryFocus : string;
export const InheritTextPrimaryMain : string;
export const InheritTextPrimaryFocusVisible : string;
export const Elevation1 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation2 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation3 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation4 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation5 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation6 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation7 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation8 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation9 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation10 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation11 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation12 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation13 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation14 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation15 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation16 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation17 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation18 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation19 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation20 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation21 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation22 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation23 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const Elevation24 : { color: string, type: string, x: number, y: number, blur: number, spread: number }[];
export const ElevationOutlined : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const FontFamiliesRoboto : string;
export const LineHeights0 : string;
export const LineHeights1 : string;
export const LineHeights2 : string;
export const LineHeights3 : string;
export const LineHeights4 : string;
export const LineHeights5 : string;
export const LineHeights6 : string;
export const LineHeights7 : string;
export const LineHeights8 : string;
export const LineHeights9 : string;
export const LineHeights10 : string;
export const LineHeights11 : number;
export const LineHeights12 : number;
export const LineHeights13 : number;
export const LineHeights14 : number;
export const LineHeights15 : number;
export const LineHeights16 : number;
export const LineHeights17 : number;
export const LineHeights18 : number;
export const FontWeightsLight : string;
export const FontWeightsRegular : string;
export const FontWeightsMedium : string;
export const FontSize0 : number;
export const FontSize1 : number;
export const FontSize2 : number;
export const FontSize3 : number;
export const FontSize4 : number;
export const FontSize5 : number;
export const FontSize6 : number;
export const FontSize7 : number;
export const FontSize8 : number;
export const FontSize9 : number;
export const FontSize10 : number;
export const FontSize11 : number;
export const LetterSpacing0 : number;
export const LetterSpacing1 : number;
export const LetterSpacing2 : number;
export const LetterSpacing3 : number;
export const LetterSpacing4 : number;
export const LetterSpacing5 : number;
export const LetterSpacing6 : number;
export const LetterSpacing7 : number;
export const LetterSpacing8 : number;
export const LetterSpacing9 : number;
export const LetterSpacing10 : number;
export const LetterSpacing11 : number;
export const ParagraphSpacingNone : number;
export const TypographyH1 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyH2 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyH3 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyH4 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyH5 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyH6 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyBody1 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyBody2 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyButton : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographySubtitle1 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographySubtitle2 : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyOverline : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TypographyCaption : { fontFamily: string, fontWeight: string, lineHeight: string, fontSize: number, letterSpacing: number, paragraphSpacing: number, paragraphIndent: number, textCase: string, textDecoration: string };
export const TextCaseNone : string;
export const TextCaseUppercase : string;
export const TextDecorationNone : string;
export const ShapeBorderRadius : number;
export const ParagraphIndentNone : number;
export const Spacing1 : number;
export const Spacing2 : number;
export const Spacing3 : number;
export const Spacing4 : number;
export const Spacing5 : number;
export const Spacing6 : number;
export const Spacing7 : number;
export const Spacing8 : number;
export const Spacing9 : number;
export const Spacing10 : number;
export const Spacing11 : number;
export const Spacing12 : number;
export const SpacingBase : number;
export const Sizing1 : number;
export const Sizing2 : number;
export const Sizing3 : number;
export const Sizing4 : number;
export const Sizing5 : number;
export const Sizing6 : number;
export const Sizing7 : number;
export const Sizing8 : number;
export const Sizing9 : number;
export const Sizing10 : number;
export const Sizing11 : number;
export const Sizing12 : number;
export const SizingBase : number;
export const BackgroundDefault : string;
export const BackgroundPaperElevation0 : string;
export const BackgroundPaperElevation1 : string;
export const BackgroundPaperElevation2 : string;
export const BackgroundPaperElevation3 : string;
export const BackgroundPaperElevation4 : string;
export const BackgroundPaperElevation5 : string;
export const BackgroundPaperElevation6 : string;
export const BackgroundPaperElevation7 : string;
export const BackgroundPaperElevation8 : string;
export const BackgroundPaperElevation9 : string;
export const BackgroundPaperElevation10 : string;
export const BackgroundPaperElevation11 : string;
export const BackgroundPaperElevation12 : string;
export const BackgroundPaperElevation13 : string;
export const BackgroundPaperElevation14 : string;
export const BackgroundPaperElevation15 : string;
export const BackgroundPaperElevation16 : string;
export const BackgroundPaperElevation17 : string;
export const BackgroundPaperElevation18 : string;
export const BackgroundPaperElevation19 : string;
export const BackgroundPaperElevation20 : string;
export const BackgroundPaperElevation21 : string;
export const BackgroundPaperElevation22 : string;
export const BackgroundPaperElevation23 : string;
export const BackgroundPaperElevation24 : string;
export const Grey50 : string;
export const Grey100 : string;
export const Grey200 : string;
export const Grey300 : string;
export const Grey400 : string;
export const Grey500 : string;
export const Grey600 : string;
export const Grey700 : string;
export const Grey800 : string;
export const Grey900 : string;
export const GreyA100 : string;
export const GreyA200 : string;
export const GreyA400 : string;
export const GreyA700 : string;
